package com.unima.risk6.game.models.enums;

public enum CountryName {
  ALASKA, NORTH_WEST_TERRITORY, ALBERTA, WESTERN_UNITED_STATES, CENTRAL_AMERICA, GREENLAND, ONTARIO, QUEBEC,
  EASTERN_UNITED_STATES, VENEZUELA, PERU, BRAZIL, ARGENTINA, ICELAND, SCANDINAVIA, UKRAINE,
  GREAT_BRITAIN, NORTHERN_EUROPE, WESTERN_EUROPE, SOUTHERN_EUROPE, NORTH_AFRICA, EGYPT, CONGO,
  EAST_AFRICA, SOUTH_AFRICA, MADAGASCAR, SIBERIA, URAL, CHINA, AFGHANISTAN, MIDDLE_EAST, INDIA,
  SIAM, YAKUTSK, IRKUTSK, MONGOLIA, JAPAN, KAMCHATKA, INDONESIA, NEW_GUINEA, WESTERN_AUSTRALIA,
  EASTERN_AUSTRALIA,
}
