package com.unima.risk6.gui.controllers.enums;


/**
 * Represents the image names used in the application. Each enum value represents a specific image.
 *
 * @author fisommer
 */

public enum ImageName {
  LOGIN_BACKGROUND,
  WON_BACKGROUND,
  SINGLEPLAYER_BACKGROUND,
  MULTIPLAYER_BACKGROUND,
  CREATE_ACCOUNT_BACKGROUND,
  OPTION_BACKGROUND,
  STATISTICS_BACKGROUND,
  SELECTED_USER_BACKGROUND,
  CREATE_LOBBY_BACKGROUND,
  SELECT_LOBBY_BACKGROUND,
  PLAYER_ICON,
  EASYBOT_ICON,
  HARDBOT_ICON,
  MEDIUMBOT_ICON,
  TUTORIAL_ICON,
  CANNON_ICON,
  INFANTRY_ICON,
  CAVALRY_ICON,
  WILDCARD_ICON,
  PLUS_ICON,
  FORTIFY_ICON,
  REINFORCE_ICON,

  SWORD_ICON, INFANTRY_RUNNING_GIF, ATTACK_DICE_PREVIEW, DICE_PREVIEW, ATTACK_DICE_ROLLING, DICE_ROLLING,

}
