package com.unima.risk6.gui.controllers.enums;

public enum ImageName {
  LOGIN_BACKGROUND,
  WON_BACKGROUND,
  SINGLEPLAYER_BACKGROUND,
  MULTIPLAYER_BACKGROUND,
  CREATE_ACCOUNT_BACKGROUND,
  OPTION_BACKGROUND,
  STATISTICS_BACKGROUND,
  SELECTED_USER_BACKGROUND,
  PLAYER_ICON,
  EASYBOT_ICON,
  HARDBOT_ICON,
  MEDIUMBOT_ICON,
  TUTORIAL_ICON
}
