package com.unima.risk6.gui.controllers.enums;

public enum SceneName {
  LOGIN,
  GAME,
  TITLE,
  SECURITY_QUESTIONS,
  CREATE_ACCOUNT,
  SELECTED_USER,
  USER_OPTION,
  USER_STATISTICS,
  SINGLE_PLAYER_SETTINGS,
  CHANGE_PASSWORD,
  MULTIPLAYER_LOBBY,
  JOIN_ONLINE,
  SELECT_LOBBY,
  CREATE_LOBBY,
  LOBBY_USER_STATISTIC,
  GAME_OVER

  // add more scene names as needed


}
