package com.unima.risk6.network.message;

public enum ConnectionActions {
  GET_GAMES, JOIN_SERVER_LOBBY, JOIN_GAME_LOBBY, JOIN_GAME, LEAVE_SERVER_LOBBY, LEAVE_GAME_LOBBY, LEAVE_GAME, CREATE_GAME, ACCEPT_USER, DROP_USER
}
