package com.unima.risk6.network.message;

public enum ConnectionActions {
  //Client Side
  JOIN_SERVER_LOBBY, JOIN_GAME_LOBBY, LEAVE_SERVER_LOBBY, LEAVE_GAME_LOBBY, LEAVE_GAME, CREATE_GAME_LOBBY, START_GAME,
  //Server Side
  ACCEPT_USER_LOBBY, DROP_USER_LOBBY, ACCEPT_USER_GAME, DROP_USER_GAME,
}
