module com.unima.risk6 {
  requires javafx.controls;
  requires javafx.fxml;
  requires javafx.media;
  requires java.sql;
  requires io.netty.codec;
  requires io.netty.codec.http;
  requires io.netty.transport;
  requires io.netty.buffer;
  requires io.netty.common;
  requires io.netty.handler;
  requires java.desktop;
  requires org.xerial.sqlitejdbc;
  requires com.google.gson;
  requires org.slf4j;
  requires com.google.common;
  opens com.unima.risk6.network.message to com.google.gson;
  opens com.unima.risk6.game.logic to com.google.gson, javafx.fxml;
  exports com.unima.risk6;
  exports com.unima.risk6.database;
  exports com.unima.risk6.database.configurations;
  exports com.unima.risk6.database.daos;
  exports com.unima.risk6.database.exceptions;
  exports com.unima.risk6.database.models;
  exports com.unima.risk6.database.repositories;
  exports com.unima.risk6.database.services;
  exports com.unima.risk6.game.ai;
  exports com.unima.risk6.game.ai.bots;
  exports com.unima.risk6.game.ai.models;
  exports com.unima.risk6.game.ai.montecarlo;
  exports com.unima.risk6.game.ai.tutorial;
  exports com.unima.risk6.game.configurations;
  exports com.unima.risk6.game.configurations.observers;
  exports com.unima.risk6.game.logic;
  exports com.unima.risk6.game.logic.controllers;
  exports com.unima.risk6.game.models;
  exports com.unima.risk6.game.models.enums;
  exports com.unima.risk6.gui.configurations;
  exports com.unima.risk6.gui.controllers;
  exports com.unima.risk6.gui.controllers.enums;
  exports com.unima.risk6.gui.scenes;
  exports com.unima.risk6.gui.uimodels;
  exports com.unima.risk6.json;
  exports com.unima.risk6.json.jsonobjects;
  exports com.unima.risk6.network.client;
  exports com.unima.risk6.network.configurations;
  exports com.unima.risk6.network.message;
  exports com.unima.risk6.network.message.enums;
  exports com.unima.risk6.network.serialization;
  exports com.unima.risk6.network.server;
  exports com.unima.risk6.network.server.exceptions;
  opens com.unima.risk6.json.jsonobjects to com.google.gson;
  opens com.unima.risk6 to javafx.fxml;
  opens com.unima.risk6.gui.controllers to javafx.fxml;
  opens com.unima.risk6.game.models to javafx.fxml, com.google.gson;
  opens com.unima.risk6.gui.controllers.enums to javafx.fxml;
  opens com.unima.risk6.network.message.enums to com.google.gson;

}